## Numpy套件ndarray型態 提供element-wise的操作



In [3]:
import numpy as np
b = np.array([1,2,3,4,5])
print(b*3) #將各個數都乘3

[ 3  6  9 12 15]


In [4]:
import numpy as np
my_2d_array=np.array(np.arange(0,10).reshape((2,5)))
print(my_2d_array)
print(my_2d_array[0,:]) #第0列元素
print(my_2d_array[1,:]) #第1列元素
print(my_2d_array[:,0]) #第0欄元素
print(my_2d_array[1,1]) #第2列2欄元素
print(my_2d_array[0,1]) #第1列2欄元素

[[0 1 2 3 4]
 [5 6 7 8 9]]
[0 1 2 3 4]
[5 6 7 8 9]
[0 5]
6
1


In [5]:
print(type(b))
print(b.ndim) #ndarray的維度
print(b.shape) #ndarray的shape
print(b.dtype) #ndarray的資料型態

<class 'numpy.ndarray'>
1
(5,)
int32


In [10]:
print(np.zeros(6)) #6元素均為0一維array
print(np.zeros((3,6))) #18元素均為0二維array
print(np.zeros((2,3,6))) #36元素均為0三維array

[0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0.]]]


In [11]:
a=np.zeros(16)
print(a)
print(a.shape)
b=a.reshape((4,4)) #改變資料的維度為4x4
print(b)
print(b.shape)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
(16,)
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(4, 4)


In [7]:
a=np.zeros(25)
print(a)
print(a.shape)
b=a.reshape((5,5)) #改變資料的維度為5x5
print(b)
print(b.shape)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0.]
(25,)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
(5, 5)


In [12]:
my_array = np.arange(10)
print(my_array)
print(my_array[0])
print(my_array[0:5]) #取0,1,2,3,4 位置的值


[0 1 2 3 4 5 6 7 8 9]
0
[0 1 2 3 4]


In [15]:
a=np.array([[0,1,2,3,4,],[5,6,7,8,9]])
print(a)
b=np.array([np.arange(0,5),np.arange(5,10)])
print(b)
c=np.array(np.arange(0,10).reshape((2,5)))
print(c)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [ ]:
## 假設有六個組別"Modern Web","DevOps","Cloud","Big Data","Security","自我挑戰組"
## 參加人數為56,8,19,14,6,71人

In [3]:
import numpy as np
groups = ["Modern Web","DevOps","Cloud","Big Data","Security","自我挑戰組"]
ironman = [56,8,19,14,6,71]
groups_array = np.array(groups)
ironman_array = np.array(ironman)
print(groups_array)
print(ironman_array)

['Modern Web' 'DevOps' 'Cloud' 'Big Data' 'Security' '自我挑戰組']
[56  8 19 14  6 71]


## 大於10人有哪些

In [4]:
#用人數去篩選組別
print(ironman_array >= 10)
print(groups_array[ironman_array >= 10])

[ True False  True  True False  True]
['Modern Web' 'Cloud' 'Big Data' '自我挑戰組']


## 除了自我挑戰組,其餘人數為何?

In [9]:
## 用組別篩選
print(groups_array != "自我挑戰組")
print(ironman_array[groups_array != "自我挑戰組"])

[ True  True  True  True  True False]
[56  8 19 14  6]


## ndarray 空值 nan 無限大 inf

In [10]:
nan_array = np.array([56,8,19,14,6,np.nan])
print(nan_array)

[56.  8. 19. 14.  6. nan]


## 生成10組標準常態分配(平均為0,標準差為1的常態分配)隨機變態

In [12]:
normal_samples = np.random.normal(size=10)
print(normal_samples)

[-1.00075383  0.45113452  0.12029543  1.38220619  1.37925271  0.21189475
  1.7491115  -0.0903255  -1.16393254 -0.79159533]


## 生成10組介於0-1之間的隨機變數

In [14]:
uniform_samples = np.random.uniform(size=10)
print(uniform_samples)

[0.44928442 0.84111079 0.19060116 0.64147599 0.86965245 0.5033339
 0.52900018 0.71601032 0.18045293 0.7421468 ]
